const CONFIG={password:'0510',coverTitle:"Imrattt's 19th Birthday ♡",letterTitle:'Happy 19th Birthday, Imrattt ♡'};const $=id=>document.getElementById(id),views=[...document.querySelectorAll('.view')];let pin='',soundOn=true,audio;
function ctx(){if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();return audio}
function tone(f=500,d=.08,type='sine',v=.035){if(!soundOn)return;try{let a=ctx(),o=a.createOscillator(),g=a.createGain();o.type=type;o.frequency.value=f;g.gain.setValueAtTime(v,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+d);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+d)}catch(e){}}
function chime(){[523,659,784,1047].forEach((f,i)=>setTimeout(()=>tone(f,.22,'sine',.045),i*95))}
function showView(id){views.forEach(v=>v.classList.toggle('active',v.id===id));scrollTo({top:0,behavior:'smooth'});tone(440,.06)}
function burst(n=80){let l=$('confetti'),cs=['#ff72b6','#7aa7ff','#ffd86e','#b892ff','#fff'];for(let i=0;i<n;i++){let p=document.createElement('i');p.className='confetti-piece';p.style.left=Math.random()*100+'vw';p.style.background=cs[i%cs.length];p.style.setProperty('--drift',(Math.random()*180-90)+'px');p.style.animationDelay=Math.random()*.4+'s';p.style.animationDuration=(2+Math.random()*2)+'s';l.appendChild(p);setTimeout(()=>p.remove(),4500)}}
function hearts(){let l=document.querySelector('.floaters');setInterval(()=>{let h=document.createElement('i');h.textContent=Math.random()>.4?'♡':'✦';h.style.left=Math.random()*100+'vw';h.style.animationDuration=(6+Math.random()*5)+'s';l.appendChild(h);setTimeout(()=>h.remove(),11000)},700)}hearts();
function dots(){document.querySelectorAll('.pin-box').forEach((b,i)=>b.innerHTML=i<pin.length?'<span>♥</span>':'')}
function submit(){if(pin.length<4)return;if(pin===CONFIG.password){$('pinMessage').textContent='Unlocked ♡';chime();burst(55);setTimeout(()=>showView('acceptView'),600)}else{$('pinMessage').textContent='Not our secret hehe ♡';tone(150,.2,'sawtooth');setTimeout(()=>{pin='';dots()},550)}}
$('playBtn').onclick=()=>{chime();showView('lockView')};$('keypad').onclick=e=>{let k=e.target.closest('button')?.dataset.key;if(!k)return;tone(320+Number(k||0)*18,.05);if(k==='clear')pin='';else if(k==='back')pin=pin.slice(0,-1);else if(pin.length<4)pin+=k;dots();submit()};
$('yesBtn').onclick=()=>{chime();burst(120);setTimeout(()=>showView('giftsView'),450)};const no=$('noBtn');function dodge(){tone(180,.05);no.style.position='absolute';no.style.left=Math.random()*55+'%';no.style.top=(Math.random()*75-10)+'px';no.textContent=['NO 🥺','are you suree? 🥹','pls hehe 😭','tap YES babyy ♡'][Math.floor(Math.random()*4)]}no.onpointerenter=dodge;no.onclick=dodge;
document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{chime();showView(b.dataset.open)});document.querySelectorAll('[data-back]').forEach(b=>b.onclick=()=>showView('giftsView'));
$('wishBtn').onclick=()=>{$('wishText').classList.add('show');burst(180);[392,523,659,784,1047].forEach((f,i)=>setTimeout(()=>tone(f,.35,'sine',.04),i*120));$('wishBtn').textContent='🕯️ Wish made for my Cutuu ♡'};
$('soundToggle').onclick=()=>{soundOn=!soundOn;$('soundToggle').textContent=soundOn?'🔊':'🔇';if(soundOn)tone(600,.08)};
$('coverTitle').textContent=CONFIG.coverTitle;$('letterDate').textContent='05 / 10 / 2026';$('letterTitle').textContent=CONFIG.letterTitle;dots();